### ISSUE TITLE
App crashes after SSH command 

### ISSUE THREAD

**Issue by F3000** [louisdh/openterm#120] opened 2018-04-15 13:12 UTC
I typ following command : 
ssh pi@10.0.0.46 -p password 

After that the app crashes ...

**Comment by holzschu** [comment] 2018-04-28 06:32
I can't reproduce the bug with the latest version of `ios_system`, which probably means it has been solved. Can someone test on OpenTerm 2.0?
"-p password" won't work anyway (this version of ssh only supports key-based authentification) but that is a different issue.

**Comment by louisdh** [comment] 2018-05-04 15:31
Seems to be fixed in the latest TestFlight beta.

**Closed by louisdh** 2018-05-04 15:31 UTC
Labels: bug
